# 1- Execute action to print "Hello World " on push
# name: hello-world
# 'on': push
# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: my-step
#         run: echo "Hello World!"
# 2- workflow flow {text,npm install,and build}
# name: React CI
# 'on': push
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version:
#           - 15.x
#     steps:
#       - uses: actions/checkout@v1
#       - run: npm install
#       - run: npm run build
#       - run: npm test
#3-Actions to lint using pretier
# name: Lint
# 'on':
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
# jobs:
#   run-linters:
#     name: Run linters
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version:
#           - 15.x
#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v1
#       - name: Run linters
#         uses: wearerequired/lint-action@v1
#         with:
#           eslint: true
#           prettier: true


# name: Prettier
# on: [push, pull_request]
# jobs:
#   prettier:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Install dependencies
#         run: npm install 
#       - name: Run prettier
#         run: npx prettier --check "**/*.{js,jsx,ts,tsx,json,md}" && echo "Prettier check passed"

name: Format code
on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Check formatting
        run: npm run check-formatting
      - name: Format code
        run: npm run format
    